- hosts: localhost
  connection: local
  vars:
    atom_upgrade_all: True
    atom_packages:
      - language-ansible
      - markdown-preview
      - language-java
      - language-yaml
      - asciidoc-preview
      - autocomplete-plus
      - git-plus
      - go-plus
      - java-plus
  roles:
     - { role: jgkim.atom }
