---
- hosts: localhost
  connection: local
  vars:
    homebrew_cask_appdir: /Applications
    homebrew_upgrade_all_packages: yes
    homebrew_installed_packages:
      - ag
      - autojump
      - cloc
      - ctags
      - ctop
      - curl
      - dos2unix
      - fasd
      - git
      - git-extras
      - git-flow
      - go
      - htop
      - httpie
      - kubectl
      - kubernetes-cli
      - maven
      - net-snmp
      - nmap
      - rpm
      - ssh-copy-id
      - the_silver_searcher
      - tiff2png
      - tmux
      - tree
      - vim
      - wget
    homebrew_taps:
      - caskroom/cask
    homebrew_cask_apps:
      - 1password
      - atom
      - chicken
      - cyberduck
      - docker
      - dropbox
      - etcher
      - firefox
      - google-chrome
      - intellij-idea-ce
      - iterm2
      - skype
      - slack
      - spotify
      - teamviewer
      - vagrant
      - virtualbox
      - visual-studio-code
      - whatsapp
  roles:
    - lidopaglia.homebrew
